# Generated by Django 3.2.13 on 2022-09-06 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 6, 10, 45, 20, 525971, tzinfo=utc), verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascotas',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoricalMascotas',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[['Macho', 'Macho'], ['Hembra', 'Hembra']], max_length=150)),
                ('edad', models.CharField(choices=[['Cachorro', 'Cachorro'], ['Adulto', 'Adulto']], max_length=150)),
                ('tamaño', models.CharField(choices=[['Grande', 'Grande'], ['Mediano', 'Mediano'], ['Pequeño', 'Pequeño']], max_length=150)),
                ('caracter', models.CharField(choices=[['Timido', 'Timido'], ['Cariñoso', 'Cariñoso'], ['Malhumorado', 'Malhumorado']], max_length=150)),
                ('castrado', models.CharField(choices=[['SI', 'SI'], ['NO', 'NO']], max_length=150)),
                ('desparacitado', models.CharField(choices=[['SI', 'SI'], ['NO', 'NO']], max_length=150)),
                ('vacunado', models.CharField(choices=[['SI', 'SI'], ['NO', 'NO']], max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mascotas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
