# Generated by Django 3.2.13 on 2022-09-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220906_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmascotas',
            name='state',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='state',
        ),
    ]
